In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
# Importing libraries
import sys
from pprint import pprint
import pandas as pd
import os
import json
import numpy as np
import pandas
from lyricsgenius import Genius


from pandas.errors import ParserError

In [3]:
list_of_files = sorted( filter( lambda x: os.path.isfile(os.path.join('../data/new_dataset', x)),
                        os.listdir('../data/new_dataset') ) )

In [5]:
lyrics_sentiments = pd.read_csv('../data/songs_lyrics_sentiments.csv')
lyrics_sentiments.head()

,Unnamed: 0.1,Unnamed: 0,artists,songs_names,lyrics,compound,neg,neu,pos
0,0,0,Felipe Araújo,Atrasadinha,"Atrasadinha (Ao Vivo) Lyrics[Letra de ""Atrasad...",-0.4314,0.010,0.990,0.000
1,1,1,MC L da Vinte,Parado no Bailão,"Parado no Bailão Lyrics[Letra de ""Parado no Ba...",-0.9868,0.204,0.725,0.071
2,2,2,Zé Neto & Cristiano,Notificação Preferida,"Notificação Preferida Lyrics[Letra de ""Notific...",0.8402,0.000,0.962,0.038
3,3,3,Marília Mendonça,Ciumeira,"Ciumeira (Ao Vivo) Lyrics[Letra de ""Ciumeira"" ...",0.4215,0.008,0.977,0.015
4,4,4,Márcia Fellipe,Quem Me Dera,"Quem Me Dera Lyrics[Letra de ""Quem Me Dera"" co...",0.0000,0.000,1.000,0.000

In [8]:
directory = '../data/new_dataset'
for filename in list_of_files:
    if filename.endswith(".csv"):
        path = directory + '/' + filename
        chart = pd.read_csv(path, encoding='utf-8', delimiter='\t')
        compound = np.zeros(chart.shape[0])
        neg = np.zeros(chart.shape[0])
        neu = np.zeros(chart.shape[0])
        pos = np.zeros(chart.shape[0])
        
        for idx, song_id in enumerate(chart['ID']):
            for idx2, song_name in enumerate(lyrics_sentiments['songs_names']):
                chart_name = chart.loc[idx, 'track_name']
                chart_name = chart_name.split(" - ", 1)
                chart_name = chart_name[0]
                if chart_name == song_name:
                    compound[idx] = lyrics_sentiments.loc[idx2, 'compound']
                    neg[idx] = lyrics_sentiments.loc[idx2, 'neg']
                    neu[idx] = lyrics_sentiments.loc[idx2, 'neu']
                    pos[idx] = lyrics_sentiments.loc[idx2, 'pos']
                    
        chart['compound'] = compound
        chart['neg'] = neg
        chart['neu'] = neu
        chart['pos'] = pos
        chart.to_csv(directory + '/' + filename)

In [9]:
compound_medias = []
neg_medias = []
neu_medias = []
pos_medias = []

In [14]:
directory = '../data/new_dataset'
for filename in list_of_files:
    if filename.endswith(".csv"):
        compound_week = []
        neg_week = []
        neu_week = []
        pos_week = []
        path = directory + '/' + filename
        chart = pd.read_csv(path)
        for idx, song_id in enumerate(chart['ID']):
            compound_week.append(chart.loc[idx, 'compound'])
            neg_week.append(chart.loc[idx, 'neg'])
            neu_week.append(chart.loc[idx, 'neu'])
            pos_week.append(chart.loc[idx, 'pos'])
                            
        compound_medias.append(np.mean(compound_week))
        neg_medias.append(np.mean(neg_week))
        neu_medias.append(np.mean(neu_week))
        pos_medias.append(np.mean(pos_week))

In [18]:
compound = pd.DataFrame({ 'compound': compound_medias})
neu = pd.DataFrame({ 'neu': neu_medias})
neg = pd.DataFrame({ 'neg': neg_medias})
pos = pd.DataFrame({ 'pos': pos_medias})

In [21]:
compound.to_csv('../data/compound.csv')
neu.to_csv('../data/neu.csv')
neg.to_csv('../data/neg.csv')
pos.to_csv('../data/pos.csv')

In [23]:
dates = pd.read_csv('../data/dates.csv')
dates.head()

   Unnamed: 0                       dates
0           0  2019-01-03T00:00:00.000000
1           1  2019-01-10T00:00:00.000000
2           2  2019-01-17T00:00:00.000000
3           3  2019-01-24T00:00:00.000000
4           4  2019-01-31T00:00:00.000000

In [25]:
compound_dates = pd.DataFrame({ 'date': dates['dates'], 'compound': compound_medias })
compound_dates.to_csv('../data/compound_dates.csv')

In [27]:
danceability = pd.read_csv('../data/danceability.csv')
danceability.head()

   Unnamed: 0                        Data  Danceability
0           0  2019-01-03T00:00:00.000000      0.693975
1           1  2019-01-10T00:00:00.000000      0.691040
2           2  2019-01-17T00:00:00.000000      0.690205
3           3  2019-01-24T00:00:00.000000      0.688690
4           4  2019-01-31T00:00:00.000000      0.687465

In [28]:
danceability_compound = pd.DataFrame({ 'danceability': danceability['Danceability'], 'compound': compound_medias })
danceability_compound.to_csv('../data/danceabilityxcompound.csv')

In [29]:
energy = pd.read_csv('../data/energy.csv')
energy.head()

   Unnamed: 0    energy
0           0  0.695050
1           1  0.685995
2           2  0.693635
3           3  0.694285
4           4  0.692455

In [30]:
energy_compound = pd.DataFrame({ 'energy': energy['energy'], 'compound': compound_medias })
energy_compound.to_csv('../data/energyxcompound.csv')

In [31]:
valence = pd.read_csv('../data/valence.csv')
valence.head()

   Unnamed: 0   valence
0           0  0.619117
1           1  0.607005
2           2  0.600952
3           3  0.602417
4           4  0.602035

In [32]:
valence_compound = pd.DataFrame({ 'valence': valence['valence'], 'compound': compound_medias })
valence_compound.to_csv('../data/valencexcompound.csv')